# Generated by Django 4.0.7 on 2023-05-04 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promotion",
            name="coffee_related",
        ),
        migrations.AddField(
            model_name="promotion",
            name="coffee_related",
            field=models.ManyToManyField(blank=True, null=True, to="core.coffee"),
        ),
    ]
