# Generated by Django 4.0.7 on 2023-05-10 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_buy_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='recharge',
            name='identification_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recharge',
            name='identification_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recharge',
            name='installments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recharge',
            name='payment_method_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recharge',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
