# Generated by Django 4.0.7 on 2023-05-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="buy_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="buys",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="orders", to="core.buy"
            ),
        ),
    ]
