# Generated by Django 4.0.7 on 2023-05-12 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_order_buy_json_alter_order_buys"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="buy_json",
        ),
    ]
