# Generated by Django 4.0.7 on 2023-05-15 04:25

import core.common.role
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_order_buy_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=django_enumfield.db.fields.EnumField(
                default=1, enum=core.common.role.Role
            ),
        ),
    ]
