# Generated by Django 4.0.7 on 2023-05-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_campain_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="campain",
            name="filters",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
